# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e07071357738f7b55ebe24247a18d790"
name = "WhatsApp Chat Widget "
application_url = "https://whatsapp-widget-production.up.railway.app/"
embedded = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "https://whatsapp-widget-production.up.railway.app/webhooks/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "offline"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://whatsapp-widget-production.up.railway.app/auth/callback"
]
